#pragma once

// Version information - automatically generated from CMake project() VERSION

#define TAXONOMYTOOLS_VERSION_MAJOR 1
#define TAXONOMYTOOLS_VERSION_MINOR 0
#define TAXONOMYTOOLS_VERSION_PATCH 0

// Helper macro to stringify version numbers
#define TAXONOMYTOOLS_STRINGIFY(x) #x
#define TAXONOMYTOOLS_TOSTRING(x) TAXONOMYTOOLS_STRINGIFY(x)

// Full version string (e.g., "1.0.0")
#define TAXONOMYTOOLS_VERSION_STRING \
    TAXONOMYTOOLS_TOSTRING(TAXONOMYTOOLS_VERSION_MAJOR) "." \
    TAXONOMYTOOLS_TOSTRING(TAXONOMYTOOLS_VERSION_MINOR) "." \
    TAXONOMYTOOLS_TOSTRING(TAXONOMYTOOLS_VERSION_PATCH)
